### PR TITLE
fix(layouts): add default to cover

### LINKED ISSUE #97: Generate complete or part of the cover slide from layout title and author
BTW, Beamer support that^^

### PR DESCRIPTION
**Pull request by Barbapapazes**
fix #97

### CODE REVIEW

**Review by aneojgurhem — DISMISSED** [review]

File: layouts/cover.vue [hunk 1]
```diff
@@ -11,12 +11,29 @@ const props = defineProps({
...
   <div class="slidev-layout cover flex flex-col justify-center items-center" :style="style">
     <div>
-      <slot />
+      <slot>
+        <h1>
+          {{ title }}
+        </h1>
+        <p>
+          {{ author }}
+          {{ author && title ? '-' : ''}}
```
Comment (Barbapapazes) [inline layouts/cover.vue:28]: `title` is useless
